name: Update App Version

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI
  push:
    branches:
      - main # Or the branch your Argo CD app is watching

jobs:
  update-and-deploy:
    runs-on: self-hosted # THIS IS THE KEY! Runs on your local Windows machine
    steps:
      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.GH_PAT }} # For pushing changes back

      - name: Set new image tag (example: using date/time for unique tag)
        id: set_tag
        run: |
          $timestamp = Get-Date -Format "yyyyMMddHHmmss"
          echo "new_tag=gcr.io/google-samples/kubernetes-bootcamp/controllermanager:v$timestamp" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Update deployment manifest with new image tag
        run: |
          $deploymentFile = "kustomize-guestbook/guestbook-ui-deployment.yaml" # Adjust path if needed
          $content = Get-Content $deploymentFile
          $content -replace 'image: gcr.io/google-samples/kubernetes-bootcamp/controllermanager:v1', "image: ${{ steps.set_tag.outputs.new_tag }}" | Set-Content $deploymentFile
        shell: pwsh

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add kustomize-guestbook/guestbook-ui-deployment.yaml # Adjust path
          git commit -m "feat: Update guestbook image to ${{ steps.set_tag.outputs.new_tag }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
