name: Build and Deploy Sample App

on:
  push:
    paths:
      - "sample-app/**"
      - "k8s/**"
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/sample-app:latest ./sample-app
          docker push ghcr.io/${{ github.repository_owner }}/sample-app:latest

      - name: Update k8s Deployment Image
        run: |
          sed -i "s|image: .*|image: ghcr.io/${{ github.repository_owner }}/sample-app:latest|g" k8s/deployment.yaml

      - name: Commit & Push Updated Manifests
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "chore: update image tag"
          git push
