name: Build and Deploy to GHCR

on:
  push:
    paths:
      - 'sample-app/**'
      - 'k8s/**'
      - '.github/workflows/update-and-deploy.yaml'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables (lowercase repo name, short SHA)
        id: vars
        run: |
          echo "repo_lower=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ steps.vars.outputs.repo_lower }}
          TAG=${{ steps.vars.outputs.sha_short }}
          docker build -t ghcr.io/${IMAGE_NAME}:${TAG} ./sample-app
          docker push ghcr.io/${IMAGE_NAME}:${TAG}

      - name: Update K8s manifest with new image tag
        run: |
          IMAGE_NAME=${{ steps.vars.outputs.repo_lower }}
          TAG=${{ steps.vars.outputs.sha_short }}
          sed -i "s|image: .*|image: ghcr.io/${IMAGE_NAME}:${TAG}|" k8s/deployment.yaml

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${{ steps.vars.outputs.sha_short }}"
          git push
