name: Build and Deploy to GHCR

on:
  push:
    paths:
      - 'sample-app/**'
      - 'k8s/**'
      - '.github/workflows/update-and-deploy.yaml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: swamyvaditya/sample-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write      # for git commit & push
      packages: write      # for pushing image to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          TAG=${{ steps.vars.outputs.sha_short }}
          docker build -t $REGISTRY/${{ env.IMAGE_NAME }}:$TAG ./sample-app
          docker push $REGISTRY/${{ env.IMAGE_NAME }}:$TAG

      - name: Update K8s manifest with new image tag
        run: |
          TAG=${{ steps.vars.outputs.sha_short }}
          sed -i "s|image: .*|image: $REGISTRY/${{ env.IMAGE_NAME }}:$TAG|" k8s/deployment.yaml

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to $TAG"
          git push
