name: Update Nginx App Version

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main
    paths:
      - '**/*.yaml'  # Trigger only on YAML changes
    exclude:
      branches:
        - main # Exclude the main branch for self-triggered pushes if needed

jobs:
  update-and-deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Set custom workspace path
        id: init
        run: |
          $workspaceRoot = "${{ github.workspace }}"
          $customWorkspace = Join-Path $workspaceRoot "_isolated-${{ github.run_id }}"
          echo "CUSTOM_WORKSPACE=$customWorkspace" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Clean custom workspace if exists
        run: |
          if (Test-Path $env:CUSTOM_WORKSPACE) {
            Remove-Item -Path $env:CUSTOM_WORKSPACE -Recurse -Force -ErrorAction SilentlyContinue
          }
          New-Item -ItemType Directory -Path $env:CUSTOM_WORKSPACE | Out-Null

      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CUSTOM_WORKSPACE }}
          set-safe-directory: false
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.GH_PAT }}

      - name: Set new image tag
        id: set_tag
        run: |
          $timestamp = Get-Date -Format "yyyyMMddHHmmss"
          echo "new_tag=nginx:$timestamp" >> $env:GITHUB_OUTPUT

      - name: Update deployment manifest with new image tag
        run: |
          $deploymentFile = Join-Path $env:CUSTOM_WORKSPACE "nginx_yaml_files\deployment.yaml"
          $currentImageRegex = 'image: nginx:.*'
          $newImage = "image: ${{ steps.set_tag.outputs.new_tag }}"

          (Get-Content $deploymentFile) -replace $currentImageRegex, $newImage | Set-Content $deploymentFile

      - name: Commit and Push Changes
        run: |
          cd $env:CUSTOM_WORKSPACE
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add nginx_yaml_files/deployment.yaml
          git commit -m "feat: Update nginx image to ${{ steps.set_tag.outputs.new_tag }} [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Clean up custom workspace (optional)
        if: always()
        run: |
          if (Test-Path $env:CUSTOM_WORKSPACE) {
            Remove-Item -Path $env:CUSTOM_WORKSPACE -Recurse -Force -ErrorAction SilentlyContinue
          }

